WIP: Creating the private locking contract
DoubleDice-com/doubledice-token pull request #4
Opened 2022-01-30 13:40 UTC by petermunachi

2022-02-03 08:19 UTC, zduniak requested changes

2022-02-03 08:19 UTC, zduniak commented on contracts/DoubleDiceUserTokenLocking.sol
> +    user.amount = user.amount + amount;
Please use += @petermunachi

2022-02-03 09:14 UTC, zduniak requested changes

2022-02-03 09:14 UTC, zduniak commented on contracts/DoubleDiceUserTokenLocking.sol
> +contract DoubleDiceUserTokenLocking is Ownable, ReentrancyGuard {
Can we rename it also to DoubleDiceLazyPoolLocking ?
(and any other references to User Token Locking in this repo and in the dApp repo, so that we have consistent names?) @petermunachi

2022-02-03 09:17 UTC, petermunachi commented on contracts/DoubleDiceUserTokenLocking.sol
> +    user.amount = user.amount + amount;
ok noted

2022-02-03 09:17 UTC, petermunachi commented on contracts/DoubleDiceUserTokenLocking.sol
> +contract DoubleDiceUserTokenLocking is Ownable, ReentrancyGuard {
ok noted

2022-02-06 11:09 UTC, zduniak requested changes

2022-02-06 11:09 UTC, zduniak commented on test/LazyPoolLocking.test.ts
> +      expect(await token.balanceOf(tokenLocking.address)).to.eq(tokenAmount.toString());
There should be assertion that makes sure this event is acually emited. As if it is not emmited the test passes, but its actually wrong.

2022-02-06 11:09 UTC, zduniak commented on test/LazyPoolLocking.test.ts
> +      expect(await token.balanceOf(tokenLocking.address)).to.eq(tokenAmount.toString());
there have to be also assertion before the lock was created, checking if the contract balance was 0 at the time, hence increased after the lock was created.

2022-02-06 11:09 UTC, zduniak commented on test/LazyPoolLocking.test.ts
> +      if (event) {
There should be assertion that makes sure this event is acually emited. As if it is not emmited the test passes, but its actually wrong.

2022-02-06 11:09 UTC, zduniak commented on test/LazyPoolLocking.test.ts
> +      ).to.eq(amount.toString());
You also use toString()'s for numerical calculations -- please correct it to BigNums

2022-02-06 11:09 UTC, zduniak commented on test/LazyPoolLocking.test.ts
> +      ).to.eq(amount.toString());
You also use toString()'s for numerical calculations -- please correct it to BigNums

2022-02-06 11:10 UTC, merged

2022-02-06 14:07 UTC, petermunachi commented on test/LazyPoolLocking.test.ts
> +      if (event) {
ok done

2022-02-06 14:14 UTC, petermunachi commented on test/LazyPoolLocking.test.ts
> +      expect(await token.balanceOf(tokenLocking.address)).to.eq(tokenAmount.toString());
done

2022-02-06 14:14 UTC, petermunachi commented on test/LazyPoolLocking.test.ts
> +      ).to.eq(amount.toString());
ok done